### ISSUE TITLE
[BUG] douyin IndexError: list index out of range

### ISSUE THREAD

**Issue by sadazs** [CharlesPikachu/videodl#19]
key = re.findall(r'/user/(.*?)\?', str(response.url))[0]
IndexError: list index out of range

**Comment by johnsonyuw** [comment]
`请输入视频链接: https://www.ted.com/talks/kathryn_kolbert_the_end_of_roe_v_wade_and_what_comes_next_for_reproductive_freedom
Traceback (most recent call last):
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/bin/videodl", line 8, in <module>
    sys.exit(videodlcmd())
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/lib/python3.9/site-packages/videodl/videodl.py", line 105, in videodlcmd
    dl_client.run()
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/lib/python3.9/site-packages/videodl/videodl.py", line 57, in run
    videoinfos = client.parse(user_input)
  File "/Users/qianguoyu/develop/py3/videodownloaderEnv/lib/python3.9/site-packages/videodl/modules/sources/ted.py", line 24, in parse
    download_url = re.findall(r'"(https://py\.tedcdn\.com/.*?).mp4', response.text)[-1]
IndexError: list index out of range
`

**Comment by CharlesPikachu** [comment]
麻烦升级到最新版本(v0.1.9)，上述问题在新版本已经修复
